src/lib/blockstore.js
While testing locally I was unable to fetch a file because the stream was being cancelled after `releaseLock` was called.
```
TypeError [ERR_INVALID_STATE]: Invalid state: The reader is not attached to a stream
at new NodeError (node:internal/errors:393:5)
at ReadableStreamDefaultReader.cancel (node:internal/webstreams/readablestream:837:28)
at #processBatch (/Users/alan/Code/web3-storage/freeway/dist/worker.mjs:24428:16) {
code: 'ERR_INVALID_STATE'
}
```
We don't need to `releaseLock` because we're the only reader so I've removed it and I no longer get this error.
=> fix: cancel after releaseLock throws INVALID_STATE error

src/index.js, src/middleware.js, test/index.spec.js
This should allow us to get freeway back into production while we fix the memory leak.
=> fix: temporarily limit the size of the response until memory leak is resolved

package-lock.json, src/bindings.d.ts, src/middleware.js, test/index.spec.js, wrangler.toml
Sets max number of car CIDs to resolve based on issue and numbers suggested in https://github.com/web3-storage/freeway/issues/22
Later on, once bigger chunks changes is largely propagated, we can consider increasing this. Also, going to create an issue to add logging to `freeway` so that we can log number of car CIDs when we throw this error back so that we can have better visibility on these numbers
=> feat: set max number of car cids to resolve

package-lock.json, package.json, scripts/r2-put.js, src/lib/blockstore.js, test/helpers.js, test/index.spec.js
Pulls in the new `gateway-lib` with the fix for allowing hash character in directory listings.
Also updates all dependencies, which includes a change in dagula to switch from our unixfs exporter fork back to `ipfs-unixfs-exporter` (since the parallel block fetching from the fork was backported).
`ipfs-unixfs-exporter` now uses `.subarray()` everywhere (no buffer copies) which is rad, but it also caused our tests to fail which was tricky to track down the cause. I've commented heavily in the place where the fix is.
=> fix: allow hash character in directory listings

src/middleware.js, wrangler.toml
Per the new sub requests max limit of 3300, increasing the maximum of shards that we attempt to get.
=> fix: update max shards values

package-lock.json, package.json, src/index.js, test/index.spec.js
This PR upgrades `gateway-lib` to support CAR block ordering.
Also fixes an issue where the CAR handler would not be invoked when using HTTP `Accept` header that had any parameters following `application/vnd.ipld.car` e.g. `application/vnd.ipld.car;order=dfs;`.
=> feat: support CAR block ordering

package-lock.json, package.json
We missed this when landing #38 ...gateway-lib uses dagula, but freeway brings it's own, and it was still using v6
fixes: https://github.com/web3-storage/freeway/issues/42
License: MIT
=> fix: update dagula to v7 for ordering support

package-lock.json, package.json, src/lib/blockstore.js, src/lib/car-index.js, test/helpers.js
Upgrade to the new version of cardex, which has a web stream-y API similar to https://github.com/ipld/js-unixfs.
=> feat: upgrade cardex

package-lock.json, package.json, scripts/r2-put.js, src/bindings.d.ts, src/index.js, src/lib/block-batch.js, src/lib/blockstore.js, src/lib/car-index.js, src/middleware.js, test/helpers.js, test/index.spec.js
This PR allows Freeway to use rollup indexes. Rollups are multi-index indexes (see https://github.com/alanshaw/cardex#multi-index-index) that specify which blocks are in which CAR file(s) for a given DAG.
Freeway checks DUDEWHERE for a rollup index at `bafyROOT/.rollup.idx`. If it finds one, it'll use it (and no other indexes) to obtain index informations for all the blocks.
=> feat: use rollup indexes

README.md, READMOAR.md, package-lock.json, package.json, src/bindings.d.ts, src/lib/blockstore.js, src/lib/car-index.js, src/middleware.js, test/helpers.js, test/index.spec.js, wrangler.toml
This PR adds support for "block link indexes" as a fallback, if content cannot be served by DUDEWHERE and SATNAV.
It binds a new bucket `BLOCKLY` (BLOCK+LYnks) and adds a new index implementation that uses the files stored in it. 
Blockly is a collection of [multi-indexes](https://github.com/web3-storage/specs/blob/73c386b999cf30fb648987ff9dce0516c1d91137/CARv2%20MultiIndex.md) for individual blocks. Each index contains the CID of a CAR file the block may be found in and the block's byte offset. The index also contains the _same detail for any links_ the block has.
=> feat: use blockly indexes

src/lib/car-index.js, test/helpers.js
The index key changed to accommodate multiple indexes of block in different CAR shards.
=> fix: blockly index key

src/middleware.js, test/index.spec.js
When there's too many shards, fallback to blockly as it is likely to be able to satisfy the request (provided indexes exist).
=> feat: fallback to blockly when shard limit exceeded

src/index.js, src/middleware.js, test/helpers/content-claims.js, test/index.spec.js
Makes content claims used by default. If no index was found from content claims, the handler is returned wrapped with the old `withIndexerSources` and `withDagula` (old)
Alternatively, we could add a new middleware and keep there the old ones. We could inspect in these middlewares if we have a dagula instance already, but I don't think that is a good way to go as we in the future can just drop this fallback
=> feat: content claims reads by default with fallback for old index sources

.github/actions/test/action.yml, package-lock.json, package.json, src/bindings.d.ts, src/handlers/rate-limiter.js, test/fixtures/worker-fixture.js, test/helpers/run-wrangler.js, test/integration/rate-limit.spec.js, test/miniflare/freeway.spec.js, test/unit/middlewares/rate-limiter.spec.js, wrangler.toml
In this PR, I have implemented an integration test setup to verify the functionality of our Cloudflare Worker. This setup involves running the worker locally with all the bindings enabled in `wrangler.toml` (`integration` environment), and performing a series of HTTP requests to ensure the worker behaves as expected under various conditions.
By running the worker locally, we avoid the complexities and overhead associated with handling authentication for deploying a remote worker via CI. This makes the testing process more straightforward.
1. **Worker Fixture**:
- **Purpose**: The fixture file contains the setup and teardown logic for the Cloudflare Worker used in our tests.
- **Functions**:
- `setupWorker`: Deploys the worker and starts the local Wrangler dev server.
- `teardownWorker`: …
=> chore: integration tests setup

.gitignore, package-lock.json, package.json, src/bindings.d.ts, src/handlers/car-block.js, src/handlers/car-block.types.ts, src/handlers/rate-limiter.js, src/handlers/rate-limiter.types.ts, test/fixtures/worker-fixture.js, test/helpers/run-wrangler.js, test/miniflare/freeway.spec.js, test/unit/middlewares/rate-limiter.spec.js, tsconfig.json
This is more what I was getting at with https://github.com/storacha/freeway/pull/116/files#r1787752932. This avoids some of the stashing and mutation by putting more inside the `new Promise()` construction itself.
I've also pulled `wranglerEnv` out into its own `const`, because it's actually an _input_, not an output. Then I've made `workerInfo` a `let` which is assigned when Wrangler boots, and is `undefined` before that, signaling that Wrangler is not yet available. The previous code was failing because there were `undefined` fields that aren't typed to allow `undefined`. Which wasn't an issue until…
I also turned type checking on in `test/`, because apparently it wasn't already. 😛 And lastly, I've ignored `.wrangler`, because Wrangler writes to that when it runs.
=> refactor: Type check and restructure tests

package-lock.json, package.json, src/middleware/withLocator.js, src/middleware/withLocator.types.ts, test/helpers/bucket.js, test/helpers/content-claims.js, test/miniflare/freeway.spec.js, wrangler.toml
Read sharded dag indexes properly, even in the absense of location claims
- use update blob-fetcher
- pass values to enable carpark fallback
- add two tests to verify:
- that normal index shard fetching works in the presence of location claims
- that in the absense of location claims it can fill in the missing values.
=> feat(blob-fetcher): use updated blob fetcher

.github/actions/test/action.yml, package-lock.json, package.json, test/miniflare/freeway.spec.js
This PR addresses an issue with resolving Node.js built-in modules (`node:buffer`, `node:events`, `node:async_hooks`) in a Cloudflare Worker Test environment. The Worker encountered errors in resolving these built-in modules, which aren’t natively supported in Workers. 
This issue was introduced when the [Opentelemetry PR was merged](https://github.com/storacha/freeway/pull/125), but we didn't see that because the Github Action that runs the `test:miniflare` was not flagging the test failure. 
During testing, the following error appeared:
```
Unable to resolve "dist/worker.mjs" dependency "node:buffer": no matching module rules.
If you're trying to import a Node.js built-in module, or an npm package that uses Node.js built-ins, you'll either need to:
- Bundle your Worker, configuring your …
```
=> fix(test): enable nodejs compat for miniflare

src/middleware/withEgressClient.js
Added the `nonce` as suggested per @alanshaw, but also set it to not expire, so we can process the invocation any time. The `servedAt` field doesn't need to be converted to seconds.
Blocked by https://github.com/storacha/w3infra/pull/443 & https://github.com/storacha/w3up/pull/1588
=> fix(egress-client): set nonce, expire and fix servedAt

wrangler.toml
Accidentally placed the KV bindings for staging under the `vars` section instead of the correct `env.staging` section.
Also fixed the missing env vars in `staging` environment, so we can track egress using the new delegation KV store.
=> fix(config): staging kv bidding

wrangler.toml
Enabled Egress Tracking in the production environment, along with the KV Delegation Store for saving and retrieving `space/content/serve/*` delegations.
=> feat: enable egress tracking in production env

src/index.js
in #131 we believed https://github.com/storacha/project-tracking/issues/176 was solved. however, it turns out updates to freeway actually just prevented tracing from getting enabled properly, and the underlying issue remained.
- bind globalthis.fetch to itself (this is the proper fix to https://github.com/storacha/project-tracking/issues/176)
- properly enable tracing
=> fix(freeway): enable tracing properly and resolve fetch issue

wrangler.toml
- Egress event was not sent to the SQS Queue in AWS, and there is no easy way to find the error with the Live Stream of requests in the Worker due to the volume of requests we receive. 
- To help troubleshoot the issue this PR enables the worker logs with 1% sampling.
=> chore(prod): enable worker logs

package.json, src/middleware/withDelegationsStorage.js, test/unit/middleware/withDelegationsStorage.spec.js
Fixed async operation bug in delegation retrieval logic
- Fixed critical bug where delegations weren't being properly awaited
- Changed `forEach` loop to `Promise.all(result.keys.map)`
- Added the `await` to ensure all delegations are fully loaded before returning results
Resolves https://github.com/storacha/freeway/issues/156
=> fix(delegationStorage): find delegations call was not returning results

src/middleware/withLocator.js, wrangler.toml
Put indexer traffic to 50% (10% seems to be doing fine)
- change prod var for indexer percentage
- also add a tag to root spans to track whether indexer was used
- remaining changes to wrangler.toml were just fixing my personal env
=> feat(freeway): put prod indexer usage to 50%

src/middleware/withCarParkFetch.js, src/middleware/withLocator.js
1. The content was uploaded before we implemented the current indexing and carpark system
2. Our current gateway tries to use the indexing service if enabled, if not, it will try to find in the carpark directly, but for some reason, it can't find it there as well
3. When neither system can find the content, the request fails, but if we disable both services, it will use content claims, and then it will find the correct location in the R2 carpark
Add a `legacyReq=true` query parameter that allows bypassing both the indexing service and carpark systems. When this parameter is present:
- The request will skip the indexing service check
- The carpark functionality will be disabled
- The content will be resolved via the content claims service
This change has been implemented in two key places: …
=> fix: handling legacy requests
